spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://LEADSGENERATION
          predicates:
            - Path=/api/**
        
        - id: api-2
          uri: lb://MOCKITOSAMPLEPROJECT
          predicates:
            - Path=/student/**
server:
  port: 3333
