
spring:
  application:
    name: LeadsGeneration
  datasource:
    url: jdbc:mysql://localhost:3306/leadgeneration
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: '*'
          auth: true
          starttls:
            enable: true
    host: smtp.gmail.com
    port: 587
    username: p.devamatha2001@gmail.com
    password: wzut htxw umcu aqrz
#  mvc:
#    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  error:
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
